# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/account_info.proto

require 'google/protobuf'

require 'rpc/v1/ledger_objects_pb'
require 'rpc/v1/amount_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/v1/account_info.proto", :syntax => :proto3) do
    add_message "rpc.v1.GetAccountInfoRequest" do
      optional :account, :message, 1, "rpc.v1.AccountAddress"
      optional :strict, :bool, 2
      optional :ledger, :message, 3, "rpc.v1.LedgerSpecifier"
      optional :queue, :bool, 4
      optional :signer_lists, :bool, 5
    end
    add_message "rpc.v1.LedgerSpecifier" do
      oneof :ledger do
        optional :shortcut, :enum, 1, "rpc.v1.LedgerSpecifier.Shortcut"
        optional :sequence, :uint32, 2
        optional :hash, :bytes, 3
      end
    end
    add_enum "rpc.v1.LedgerSpecifier.Shortcut" do
      value :SHORTCUT_UNSPECIFIED, 0
      value :SHORTCUT_VALIDATED, 1
      value :SHORTCUT_CLOSED, 2
      value :SHORTCUT_CURRENT, 3
    end
    add_message "rpc.v1.GetAccountInfoResponse" do
      optional :account_data, :message, 1, "rpc.v1.AccountRoot"
      optional :signer_list, :message, 2, "rpc.v1.SignerList"
      optional :ledger_index, :uint32, 3
      optional :queue_data, :message, 4, "rpc.v1.QueueData"
      optional :validated, :bool, 5
    end
    add_message "rpc.v1.QueueData" do
      optional :txn_count, :uint32, 1
      optional :auth_change_queued, :bool, 2
      optional :lowest_sequence, :uint32, 3
      optional :highest_sequence, :uint32, 4
      optional :max_spend_drops_total, :message, 5, "rpc.v1.XRPDropsAmount"
      repeated :transactions, :message, 6, "rpc.v1.QueuedTransaction"
    end
    add_message "rpc.v1.QueuedTransaction" do
      optional :auth_change, :bool, 1
      optional :fee, :message, 2, "rpc.v1.XRPDropsAmount"
      optional :fee_level, :uint64, 3
      optional :max_spend_drops, :message, 4, "rpc.v1.XRPDropsAmount"
      optional :sequence, :uint32, 5
      optional :last_ledger_sequence, :uint32, 6
    end
  end
end

module Rpc
  module V1
    GetAccountInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.GetAccountInfoRequest").msgclass
    LedgerSpecifier = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.LedgerSpecifier").msgclass
    LedgerSpecifier::Shortcut = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.LedgerSpecifier.Shortcut").enummodule
    GetAccountInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.GetAccountInfoResponse").msgclass
    QueueData = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.QueueData").msgclass
    QueuedTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.QueuedTransaction").msgclass
  end
end
