# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/amount.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/v1/amount.proto", :syntax => :proto3) do
    add_message "rpc.v1.CurrencyAmount" do
      oneof :amount do
        optional :xrp_amount, :message, 1, "rpc.v1.XRPDropsAmount"
        optional :issued_currency_amount, :message, 2, "rpc.v1.IssuedCurrencyAmount"
      end
    end
    add_message "rpc.v1.XRPDropsAmount" do
      optional :drops, :uint64, 1
    end
    add_message "rpc.v1.AccountAddress" do
      optional :address, :string, 1
    end
    add_message "rpc.v1.IssuedCurrencyAmount" do
      optional :currency, :message, 1, "rpc.v1.Currency"
      optional :value, :string, 2
      optional :issuer, :message, 3, "rpc.v1.AccountAddress"
    end
    add_message "rpc.v1.Currency" do
      optional :name, :string, 1
      optional :code, :bytes, 2
    end
  end
end

module Rpc
  module V1
    CurrencyAmount = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.CurrencyAmount").msgclass
    XRPDropsAmount = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.XRPDropsAmount").msgclass
    AccountAddress = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.AccountAddress").msgclass
    IssuedCurrencyAmount = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.IssuedCurrencyAmount").msgclass
    Currency = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Currency").msgclass
  end
end
