# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/meta.proto

require 'google/protobuf'

require 'rpc/v1/amount_pb'
require 'rpc/v1/ledger_objects_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/v1/meta.proto", :syntax => :proto3) do
    add_message "rpc.v1.Meta" do
      optional :transaction_index, :uint64, 1
      optional :transaction_result, :message, 2, "rpc.v1.TransactionResult"
      repeated :affected_nodes, :message, 3, "rpc.v1.AffectedNode"
      optional :delivered_amount, :message, 4, "rpc.v1.CurrencyAmount"
    end
    add_message "rpc.v1.TransactionResult" do
      optional :result_type, :enum, 1, "rpc.v1.TransactionResult.ResultType"
      optional :result, :string, 2
    end
    add_enum "rpc.v1.TransactionResult.ResultType" do
      value :RESULT_TYPE_UNSPECIFIED, 0
      value :RESULT_TYPE_TEC, 1
      value :RESULT_TYPE_TEF, 2
      value :RESULT_TYPE_TEL, 3
      value :RESULT_TYPE_TEM, 4
      value :RESULT_TYPE_TER, 5
      value :RESULT_TYPE_TES, 6
    end
    add_message "rpc.v1.AffectedNode" do
      optional :ledger_entry_type, :enum, 1, "rpc.v1.LedgerEntryType"
      optional :ledger_index, :bytes, 2
      oneof :node do
        optional :created_node, :message, 3, "rpc.v1.CreatedNode"
        optional :deleted_node, :message, 4, "rpc.v1.DeletedNode"
        optional :modified_node, :message, 5, "rpc.v1.ModifiedNode"
      end
    end
    add_message "rpc.v1.CreatedNode" do
      optional :new_fields, :message, 1, "rpc.v1.LedgerObject"
    end
    add_message "rpc.v1.DeletedNode" do
      optional :final_fields, :message, 1, "rpc.v1.LedgerObject"
    end
    add_message "rpc.v1.ModifiedNode" do
      optional :final_fields, :message, 1, "rpc.v1.LedgerObject"
      optional :previous_fields, :message, 2, "rpc.v1.LedgerObject"
      optional :previous_transaction_id, :bytes, 3
      optional :previous_transaction_ledger_sequence, :uint32, 4
    end
  end
end

module Rpc
  module V1
    Meta = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Meta").msgclass
    TransactionResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.TransactionResult").msgclass
    TransactionResult::ResultType = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.TransactionResult.ResultType").enummodule
    AffectedNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.AffectedNode").msgclass
    CreatedNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.CreatedNode").msgclass
    DeletedNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.DeletedNode").msgclass
    ModifiedNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.ModifiedNode").msgclass
  end
end
