# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/transaction.proto

require 'google/protobuf'

require 'rpc/v1/amount_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/v1/transaction.proto", :syntax => :proto3) do
    add_message "rpc.v1.Transaction" do
      optional :account, :message, 1, "rpc.v1.AccountAddress"
      optional :fee, :message, 2, "rpc.v1.XRPDropsAmount"
      optional :sequence, :uint32, 3
      optional :signing_public_key, :bytes, 5
      optional :signature, :bytes, 6
      optional :flags, :uint32, 7
      optional :last_ledger_sequence, :uint32, 8
      optional :source_tag, :uint32, 9
      repeated :memos, :message, 10, "rpc.v1.Memo"
      repeated :signers, :message, 11, "rpc.v1.Signer"
      optional :account_transaction_id, :bytes, 12
      oneof :transaction_data do
        optional :payment, :message, 4, "rpc.v1.Payment"
      end
    end
    add_message "rpc.v1.Memo" do
      optional :memo_data, :bytes, 1
      optional :memo_format, :bytes, 2
      optional :memo_type, :bytes, 3
    end
    add_message "rpc.v1.Signer" do
      optional :account, :message, 1, "rpc.v1.AccountAddress"
      optional :transaction_signature, :bytes, 2
      optional :signing_public_key, :bytes, 3
    end
    add_message "rpc.v1.Payment" do
      optional :amount, :message, 1, "rpc.v1.CurrencyAmount"
      optional :destination, :message, 2, "rpc.v1.AccountAddress"
      optional :destination_tag, :uint32, 3
      optional :invoice_id, :bytes, 4
      repeated :paths, :message, 5, "rpc.v1.Path"
      optional :send_max, :message, 6, "rpc.v1.CurrencyAmount"
      optional :deliver_min, :message, 7, "rpc.v1.CurrencyAmount"
    end
    add_message "rpc.v1.Path" do
      repeated :elements, :message, 1, "rpc.v1.PathElement"
    end
    add_message "rpc.v1.PathElement" do
      optional :account, :message, 1, "rpc.v1.AccountAddress"
      optional :currency, :message, 2, "rpc.v1.Currency"
      optional :issuer, :message, 3, "rpc.v1.AccountAddress"
    end
  end
end

module Rpc
  module V1
    Transaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Transaction").msgclass
    Memo = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Memo").msgclass
    Signer = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Signer").msgclass
    Payment = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Payment").msgclass
    Path = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.Path").msgclass
    PathElement = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.PathElement").msgclass
  end
end
