# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/xrp_ledger.proto

require 'google/protobuf'

require 'rpc/v1/account_info_pb'
require 'rpc/v1/fee_pb'
require 'rpc/v1/submit_pb'
require 'rpc/v1/tx_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/v1/xrp_ledger.proto", :syntax => :proto3) do
  end
end

module Rpc
  module V1
  end
end
