# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_fee_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("get_fee_request.proto", :syntax => :proto3) do
    add_message "io.xpring.GetFeeRequest" do
    end
  end
end

module Io
  module Xpring
    GetFeeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.GetFeeRequest").msgclass
  end
end
