# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_transaction_status_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("get_transaction_status_request.proto", :syntax => :proto3) do
    add_message "io.xpring.GetTransactionStatusRequest" do
      optional :transaction_hash, :string, 1
    end
  end
end

module Io
  module Xpring
    GetTransactionStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.GetTransactionStatusRequest").msgclass
  end
end
