# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_account_info_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("get_account_info_request.proto", :syntax => :proto3) do
    add_message "io.xpring.GetAccountInfoRequest" do
      optional :address, :string, 1
    end
  end
end

module Io
  module Xpring
    GetAccountInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.GetAccountInfoRequest").msgclass
  end
end
