# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

require 'google/protobuf'

require 'fiat_amount_pb'
require 'xrp_amount_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("payment.proto", :syntax => :proto3) do
    add_message "io.xpring.Payment" do
      optional :destination, :string, 3
      oneof :amount do
        optional :xrp_amount, :message, 1, "io.xpring.XRPAmount"
        optional :fiat_amount, :message, 2, "io.xpring.FiatAmount"
      end
    end
  end
end

module Io
  module Xpring
    Payment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.Payment").msgclass
  end
end
