# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

require 'google/protobuf'

require 'payment_pb'
require 'xrp_amount_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("transaction.proto", :syntax => :proto3) do
    add_message "io.xpring.Transaction" do
      optional :account, :string, 1
      optional :fee, :message, 2, "io.xpring.XRPAmount"
      optional :sequence, :uint64, 3
      optional :signing_public_key_hex, :string, 5
      optional :last_ledger_sequence, :uint32, 6
      oneof :transaction_data do
        optional :payment, :message, 4, "io.xpring.Payment"
      end
    end
  end
end

module Io
  module Xpring
    Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.Transaction").msgclass
  end
end
