# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xrp_amount.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xrp_amount.proto", :syntax => :proto3) do
    add_message "io.xpring.XRPAmount" do
      optional :drops, :string, 1
    end
  end
end

module Io
  module Xpring
    XRPAmount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.XRPAmount").msgclass
  end
end
