# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xrp_ledger.proto

require 'google/protobuf'

require 'account_info_pb'
require 'fee_pb'
require 'get_account_info_request_pb'
require 'get_fee_request_pb'
require 'get_latest_validated_ledger_sequence_request_pb'
require 'get_transaction_status_request_pb'
require 'ledger_sequence_pb'
require 'submit_signed_transaction_request_pb'
require 'submit_signed_transaction_response_pb'
require 'transaction_status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xrp_ledger.proto", :syntax => :proto3) do
  end
end

module Io
  module Xpring
  end
end
