# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fiat_amount.proto

require 'google/protobuf'

require 'currency_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fiat_amount.proto", :syntax => :proto3) do
    add_message "io.xpring.FiatAmount" do
      optional :currency, :enum, 1, "io.xpring.Currency"
      optional :value, :string, 2
      optional :issuer, :string, 3
    end
  end
end

module Io
  module Xpring
    FiatAmount = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.FiatAmount").msgclass
  end
end
