# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger_sequence.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ledger_sequence.proto", :syntax => :proto3) do
    add_message "io.xpring.LedgerSequence" do
      optional :index, :uint32, 1
    end
  end
end

module Io
  module Xpring
    LedgerSequence = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.LedgerSequence").msgclass
  end
end
