# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: submit_signed_transaction_request.proto

require 'google/protobuf'

require 'signed_transaction_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("submit_signed_transaction_request.proto", :syntax => :proto3) do
    add_message "io.xpring.SubmitSignedTransactionRequest" do
      optional :signed_transaction, :message, 1, "io.xpring.SignedTransaction"
    end
  end
end

module Io
  module Xpring
    SubmitSignedTransactionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.xpring.SubmitSignedTransactionRequest").msgclass
  end
end
