# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/account.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/account.proto", :syntax => :proto3) do
    add_message "org.xrpl.rpc.v1.AccountAddress" do
      optional :address, :string, 1
    end
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
        AccountAddress = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.AccountAddress").msgclass
      end
    end
  end
end
