# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/get_account_transaction_history.proto

require 'google/protobuf'

require 'org/xrpl/rpc/v1/get_transaction_pb'
require 'org/xrpl/rpc/v1/account_pb'
require 'org/xrpl/rpc/v1/ledger_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/get_account_transaction_history.proto", :syntax => :proto3) do
    add_message "org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest" do
      optional :account, :message, 1, "org.xrpl.rpc.v1.AccountAddress"
      optional :binary, :bool, 4
      optional :forward, :bool, 5
      optional :limit, :uint32, 6
      optional :marker, :message, 7, "org.xrpl.rpc.v1.Marker"
      oneof :ledger do
        optional :ledger_specifier, :message, 2, "org.xrpl.rpc.v1.LedgerSpecifier"
        optional :ledger_range, :message, 3, "org.xrpl.rpc.v1.LedgerRange"
      end
    end
    add_message "org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse" do
      optional :account, :message, 1, "org.xrpl.rpc.v1.AccountAddress"
      optional :ledger_index_min, :uint32, 2
      optional :ledger_index_max, :uint32, 3
      optional :limit, :uint32, 4
      optional :marker, :message, 5, "org.xrpl.rpc.v1.Marker"
      repeated :transactions, :message, 6, "org.xrpl.rpc.v1.GetTransactionResponse"
      optional :validated, :bool, 7
    end
    add_message "org.xrpl.rpc.v1.Marker" do
      optional :ledger_index, :uint32, 1
      optional :account_sequence, :uint32, 2
    end
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
        GetAccountTransactionHistoryRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.GetAccountTransactionHistoryRequest").msgclass
        GetAccountTransactionHistoryResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.GetAccountTransactionHistoryResponse").msgclass
        Marker = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Marker").msgclass
      end
    end
  end
end
