# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/get_transaction.proto

require 'google/protobuf'

require 'org/xrpl/rpc/v1/meta_pb'
require 'org/xrpl/rpc/v1/ledger_pb'
require 'org/xrpl/rpc/v1/transaction_pb'
require 'org/xrpl/rpc/v1/common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/get_transaction.proto", :syntax => :proto3) do
    add_message "org.xrpl.rpc.v1.GetTransactionRequest" do
      optional :hash, :bytes, 1
      optional :binary, :bool, 2
      optional :ledger_range, :message, 3, "org.xrpl.rpc.v1.LedgerRange"
    end
    add_message "org.xrpl.rpc.v1.GetTransactionResponse" do
      optional :ledger_index, :uint32, 3
      optional :hash, :bytes, 4
      optional :validated, :bool, 5
      optional :date, :message, 8, "org.xrpl.rpc.v1.Date"
      oneof :serialized_transaction do
        optional :transaction, :message, 1, "org.xrpl.rpc.v1.Transaction"
        optional :transaction_binary, :bytes, 2
      end
      oneof :serialized_meta do
        optional :meta, :message, 6, "org.xrpl.rpc.v1.Meta"
        optional :meta_binary, :bytes, 7
      end
    end
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
        GetTransactionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.GetTransactionRequest").msgclass
        GetTransactionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.GetTransactionResponse").msgclass
      end
    end
  end
end
