# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/get_account_info.proto

require 'google/protobuf'

require 'org/xrpl/rpc/v1/ledger_objects_pb'
require 'org/xrpl/rpc/v1/amount_pb'
require 'org/xrpl/rpc/v1/account_pb'
require 'org/xrpl/rpc/v1/ledger_pb'
require 'org/xrpl/rpc/v1/common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/get_account_info.proto", :syntax => :proto3) do
    add_message "org.xrpl.rpc.v1.GetAccountInfoRequest" do
      optional :account, :message, 1, "org.xrpl.rpc.v1.AccountAddress"
      optional :strict, :bool, 2
      optional :ledger, :message, 3, "org.xrpl.rpc.v1.LedgerSpecifier"
      optional :queue, :bool, 4
      optional :signer_lists, :bool, 5
    end
    add_message "org.xrpl.rpc.v1.GetAccountInfoResponse" do
      optional :account_data, :message, 1, "org.xrpl.rpc.v1.AccountRoot"
      optional :signer_list, :message, 2, "org.xrpl.rpc.v1.SignerList"
      optional :ledger_index, :uint32, 3
      optional :queue_data, :message, 4, "org.xrpl.rpc.v1.QueueData"
      optional :validated, :bool, 5
    end
    add_message "org.xrpl.rpc.v1.QueueData" do
      optional :txn_count, :uint32, 1
      optional :auth_change_queued, :bool, 2
      optional :lowest_sequence, :uint32, 3
      optional :highest_sequence, :uint32, 4
      optional :max_spend_drops_total, :message, 5, "org.xrpl.rpc.v1.XRPDropsAmount"
      repeated :transactions, :message, 6, "org.xrpl.rpc.v1.QueuedTransaction"
    end
    add_message "org.xrpl.rpc.v1.QueuedTransaction" do
      optional :auth_change, :bool, 1
      optional :fee, :message, 2, "org.xrpl.rpc.v1.XRPDropsAmount"
      optional :fee_level, :uint64, 3
      optional :max_spend_drops, :message, 4, "org.xrpl.rpc.v1.XRPDropsAmount"
      optional :sequence, :message, 5, "org.xrpl.rpc.v1.Sequence"
      optional :last_ledger_sequence, :message, 6, "org.xrpl.rpc.v1.LastLedgerSequence"
    end
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
        GetAccountInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.GetAccountInfoRequest").msgclass
        GetAccountInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.GetAccountInfoResponse").msgclass
        QueueData = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.QueueData").msgclass
        QueuedTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.QueuedTransaction").msgclass
      end
    end
  end
end
