# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/ledger.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/ledger.proto", :syntax => :proto3) do
    add_message "org.xrpl.rpc.v1.LedgerSpecifier" do
      oneof :ledger do
        optional :shortcut, :enum, 1, "org.xrpl.rpc.v1.LedgerSpecifier.Shortcut"
        optional :sequence, :uint32, 2
        optional :hash, :bytes, 3
      end
    end
    add_enum "org.xrpl.rpc.v1.LedgerSpecifier.Shortcut" do
      value :SHORTCUT_UNSPECIFIED, 0
      value :SHORTCUT_VALIDATED, 1
      value :SHORTCUT_CLOSED, 2
      value :SHORTCUT_CURRENT, 3
    end
    add_message "org.xrpl.rpc.v1.LedgerRange" do
      optional :ledger_index_min, :uint32, 1
      optional :ledger_index_max, :uint32, 2
    end
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
        LedgerSpecifier = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.LedgerSpecifier").msgclass
        LedgerSpecifier::Shortcut = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.LedgerSpecifier.Shortcut").enummodule
        LedgerRange = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.LedgerRange").msgclass
      end
    end
  end
end
