# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/transaction.proto

require 'google/protobuf'

require 'org/xrpl/rpc/v1/common_pb'
require 'org/xrpl/rpc/v1/amount_pb'
require 'org/xrpl/rpc/v1/account_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/transaction.proto", :syntax => :proto3) do
    add_message "org.xrpl.rpc.v1.Transaction" do
      optional :account, :message, 1, "org.xrpl.rpc.v1.Account"
      optional :fee, :message, 2, "org.xrpl.rpc.v1.XRPDropsAmount"
      optional :sequence, :message, 3, "org.xrpl.rpc.v1.Sequence"
      optional :signing_public_key, :message, 5, "org.xrpl.rpc.v1.SigningPublicKey"
      optional :transaction_signature, :message, 6, "org.xrpl.rpc.v1.TransactionSignature"
      optional :flags, :message, 7, "org.xrpl.rpc.v1.Flags"
      optional :last_ledger_sequence, :message, 8, "org.xrpl.rpc.v1.LastLedgerSequence"
      optional :source_tag, :message, 9, "org.xrpl.rpc.v1.SourceTag"
      repeated :memos, :message, 10, "org.xrpl.rpc.v1.Memo"
      repeated :signers, :message, 11, "org.xrpl.rpc.v1.Signer"
      optional :account_transaction_id, :message, 12, "org.xrpl.rpc.v1.AccountTransactionID"
      optional :ticket_sequence, :message, 31, "org.xrpl.rpc.v1.TicketSequence"
      oneof :transaction_data do
        optional :payment, :message, 4, "org.xrpl.rpc.v1.Payment"
        optional :account_set, :message, 13, "org.xrpl.rpc.v1.AccountSet"
        optional :account_delete, :message, 14, "org.xrpl.rpc.v1.AccountDelete"
        optional :check_cancel, :message, 15, "org.xrpl.rpc.v1.CheckCancel"
        optional :check_cash, :message, 16, "org.xrpl.rpc.v1.CheckCash"
        optional :check_create, :message, 17, "org.xrpl.rpc.v1.CheckCreate"
        optional :deposit_preauth, :message, 18, "org.xrpl.rpc.v1.DepositPreauth"
        optional :escrow_cancel, :message, 19, "org.xrpl.rpc.v1.EscrowCancel"
        optional :escrow_create, :message, 20, "org.xrpl.rpc.v1.EscrowCreate"
        optional :escrow_finish, :message, 21, "org.xrpl.rpc.v1.EscrowFinish"
        optional :offer_cancel, :message, 22, "org.xrpl.rpc.v1.OfferCancel"
        optional :offer_create, :message, 23, "org.xrpl.rpc.v1.OfferCreate"
        optional :payment_channel_claim, :message, 24, "org.xrpl.rpc.v1.PaymentChannelClaim"
        optional :payment_channel_create, :message, 25, "org.xrpl.rpc.v1.PaymentChannelCreate"
        optional :payment_channel_fund, :message, 26, "org.xrpl.rpc.v1.PaymentChannelFund"
        optional :set_regular_key, :message, 27, "org.xrpl.rpc.v1.SetRegularKey"
        optional :signer_list_set, :message, 28, "org.xrpl.rpc.v1.SignerListSet"
        optional :ticket_create, :message, 30, "org.xrpl.rpc.v1.TicketCreate"
        optional :trust_set, :message, 29, "org.xrpl.rpc.v1.TrustSet"
      end
    end
    add_message "org.xrpl.rpc.v1.Memo" do
      optional :memo_data, :message, 1, "org.xrpl.rpc.v1.MemoData"
      optional :memo_format, :message, 2, "org.xrpl.rpc.v1.MemoFormat"
      optional :memo_type, :message, 3, "org.xrpl.rpc.v1.MemoType"
    end
    add_message "org.xrpl.rpc.v1.Signer" do
      optional :account, :message, 1, "org.xrpl.rpc.v1.Account"
      optional :transaction_signature, :message, 2, "org.xrpl.rpc.v1.TransactionSignature"
      optional :signing_public_key, :message, 3, "org.xrpl.rpc.v1.SigningPublicKey"
    end
    add_message "org.xrpl.rpc.v1.AccountSet" do
      optional :clear_flag, :message, 1, "org.xrpl.rpc.v1.ClearFlag"
      optional :domain, :message, 2, "org.xrpl.rpc.v1.Domain"
      optional :email_hash, :message, 3, "org.xrpl.rpc.v1.EmailHash"
      optional :message_key, :message, 4, "org.xrpl.rpc.v1.MessageKey"
      optional :set_flag, :message, 5, "org.xrpl.rpc.v1.SetFlag"
      optional :transfer_rate, :message, 6, "org.xrpl.rpc.v1.TransferRate"
      optional :tick_size, :message, 7, "org.xrpl.rpc.v1.TickSize"
    end
    add_message "org.xrpl.rpc.v1.AccountDelete" do
      optional :destination, :message, 1, "org.xrpl.rpc.v1.Destination"
      optional :destination_tag, :message, 2, "org.xrpl.rpc.v1.DestinationTag"
    end
    add_message "org.xrpl.rpc.v1.CheckCancel" do
      optional :check_id, :message, 1, "org.xrpl.rpc.v1.CheckID"
    end
    add_message "org.xrpl.rpc.v1.CheckCash" do
      optional :check_id, :message, 1, "org.xrpl.rpc.v1.CheckID"
      oneof :amount_oneof do
        optional :amount, :message, 2, "org.xrpl.rpc.v1.Amount"
        optional :deliver_min, :message, 3, "org.xrpl.rpc.v1.DeliverMin"
      end
    end
    add_message "org.xrpl.rpc.v1.CheckCreate" do
      optional :destination, :message, 1, "org.xrpl.rpc.v1.Destination"
      optional :send_max, :message, 2, "org.xrpl.rpc.v1.SendMax"
      optional :destination_tag, :message, 3, "org.xrpl.rpc.v1.DestinationTag"
      optional :expiration, :message, 4, "org.xrpl.rpc.v1.Expiration"
      optional :invoice_id, :message, 5, "org.xrpl.rpc.v1.InvoiceID"
    end
    add_message "org.xrpl.rpc.v1.DepositPreauth" do
      oneof :authorization_oneof do
        optional :authorize, :message, 1, "org.xrpl.rpc.v1.Authorize"
        optional :unauthorize, :message, 2, "org.xrpl.rpc.v1.Unauthorize"
      end
    end
    add_message "org.xrpl.rpc.v1.EscrowCancel" do
      optional :owner, :message, 1, "org.xrpl.rpc.v1.Owner"
      optional :offer_sequence, :message, 2, "org.xrpl.rpc.v1.OfferSequence"
    end
    add_message "org.xrpl.rpc.v1.EscrowCreate" do
      optional :amount, :message, 1, "org.xrpl.rpc.v1.Amount"
      optional :destination, :message, 2, "org.xrpl.rpc.v1.Destination"
      optional :cancel_after, :message, 3, "org.xrpl.rpc.v1.CancelAfter"
      optional :finish_after, :message, 4, "org.xrpl.rpc.v1.FinishAfter"
      optional :condition, :message, 5, "org.xrpl.rpc.v1.Condition"
      optional :destination_tag, :message, 6, "org.xrpl.rpc.v1.DestinationTag"
    end
    add_message "org.xrpl.rpc.v1.EscrowFinish" do
      optional :owner, :message, 1, "org.xrpl.rpc.v1.Owner"
      optional :offer_sequence, :message, 2, "org.xrpl.rpc.v1.OfferSequence"
      optional :condition, :message, 3, "org.xrpl.rpc.v1.Condition"
      optional :fulfillment, :message, 4, "org.xrpl.rpc.v1.Fulfillment"
    end
    add_message "org.xrpl.rpc.v1.OfferCancel" do
      optional :offer_sequence, :message, 1, "org.xrpl.rpc.v1.OfferSequence"
    end
    add_message "org.xrpl.rpc.v1.OfferCreate" do
      optional :expiration, :message, 1, "org.xrpl.rpc.v1.Expiration"
      optional :offer_sequence, :message, 2, "org.xrpl.rpc.v1.OfferSequence"
      optional :taker_gets, :message, 3, "org.xrpl.rpc.v1.TakerGets"
      optional :taker_pays, :message, 4, "org.xrpl.rpc.v1.TakerPays"
    end
    add_message "org.xrpl.rpc.v1.Payment" do
      optional :amount, :message, 1, "org.xrpl.rpc.v1.Amount"
      optional :destination, :message, 2, "org.xrpl.rpc.v1.Destination"
      optional :destination_tag, :message, 3, "org.xrpl.rpc.v1.DestinationTag"
      optional :invoice_id, :message, 4, "org.xrpl.rpc.v1.InvoiceID"
      repeated :paths, :message, 5, "org.xrpl.rpc.v1.Payment.Path"
      optional :send_max, :message, 6, "org.xrpl.rpc.v1.SendMax"
      optional :deliver_min, :message, 7, "org.xrpl.rpc.v1.DeliverMin"
    end
    add_message "org.xrpl.rpc.v1.Payment.PathElement" do
      optional :account, :message, 1, "org.xrpl.rpc.v1.AccountAddress"
      optional :currency, :message, 2, "org.xrpl.rpc.v1.Currency"
      optional :issuer, :message, 3, "org.xrpl.rpc.v1.AccountAddress"
    end
    add_message "org.xrpl.rpc.v1.Payment.Path" do
      repeated :elements, :message, 1, "org.xrpl.rpc.v1.Payment.PathElement"
    end
    add_message "org.xrpl.rpc.v1.PaymentChannelClaim" do
      optional :channel, :message, 1, "org.xrpl.rpc.v1.Channel"
      optional :balance, :message, 2, "org.xrpl.rpc.v1.Balance"
      optional :amount, :message, 3, "org.xrpl.rpc.v1.Amount"
      optional :payment_channel_signature, :message, 4, "org.xrpl.rpc.v1.PaymentChannelSignature"
      optional :public_key, :message, 5, "org.xrpl.rpc.v1.PublicKey"
    end
    add_message "org.xrpl.rpc.v1.PaymentChannelCreate" do
      optional :amount, :message, 1, "org.xrpl.rpc.v1.Amount"
      optional :destination, :message, 2, "org.xrpl.rpc.v1.Destination"
      optional :settle_delay, :message, 3, "org.xrpl.rpc.v1.SettleDelay"
      optional :public_key, :message, 4, "org.xrpl.rpc.v1.PublicKey"
      optional :cancel_after, :message, 5, "org.xrpl.rpc.v1.CancelAfter"
      optional :destination_tag, :message, 6, "org.xrpl.rpc.v1.DestinationTag"
    end
    add_message "org.xrpl.rpc.v1.PaymentChannelFund" do
      optional :channel, :message, 1, "org.xrpl.rpc.v1.Channel"
      optional :amount, :message, 2, "org.xrpl.rpc.v1.Amount"
      optional :expiration, :message, 3, "org.xrpl.rpc.v1.Expiration"
    end
    add_message "org.xrpl.rpc.v1.SetRegularKey" do
      optional :regular_key, :message, 1, "org.xrpl.rpc.v1.RegularKey"
    end
    add_message "org.xrpl.rpc.v1.SignerListSet" do
      optional :signer_quorum, :message, 1, "org.xrpl.rpc.v1.SignerQuorum"
      repeated :signer_entries, :message, 2, "org.xrpl.rpc.v1.SignerEntry"
    end
    add_message "org.xrpl.rpc.v1.TicketCreate" do
      optional :count, :message, 1, "org.xrpl.rpc.v1.TicketCount"
    end
    add_message "org.xrpl.rpc.v1.TrustSet" do
      optional :limit_amount, :message, 1, "org.xrpl.rpc.v1.LimitAmount"
      optional :quality_in, :message, 2, "org.xrpl.rpc.v1.QualityIn"
      optional :quality_out, :message, 3, "org.xrpl.rpc.v1.QualityOut"
    end
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
        Transaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Transaction").msgclass
        Memo = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Memo").msgclass
        Signer = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Signer").msgclass
        AccountSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.AccountSet").msgclass
        AccountDelete = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.AccountDelete").msgclass
        CheckCancel = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.CheckCancel").msgclass
        CheckCash = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.CheckCash").msgclass
        CheckCreate = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.CheckCreate").msgclass
        DepositPreauth = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.DepositPreauth").msgclass
        EscrowCancel = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.EscrowCancel").msgclass
        EscrowCreate = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.EscrowCreate").msgclass
        EscrowFinish = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.EscrowFinish").msgclass
        OfferCancel = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.OfferCancel").msgclass
        OfferCreate = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.OfferCreate").msgclass
        Payment = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Payment").msgclass
        Payment::PathElement = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Payment.PathElement").msgclass
        Payment::Path = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.Payment.Path").msgclass
        PaymentChannelClaim = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.PaymentChannelClaim").msgclass
        PaymentChannelCreate = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.PaymentChannelCreate").msgclass
        PaymentChannelFund = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.PaymentChannelFund").msgclass
        SetRegularKey = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.SetRegularKey").msgclass
        SignerListSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.SignerListSet").msgclass
        TicketCreate = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.TicketCreate").msgclass
        TrustSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("org.xrpl.rpc.v1.TrustSet").msgclass
      end
    end
  end
end
