# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/xrpl/rpc/v1/xrp_ledger.proto

require 'google/protobuf'

require 'org/xrpl/rpc/v1/get_account_info_pb'
require 'org/xrpl/rpc/v1/get_fee_pb'
require 'org/xrpl/rpc/v1/submit_pb'
require 'org/xrpl/rpc/v1/get_transaction_pb'
require 'org/xrpl/rpc/v1/get_account_transaction_history_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("org/xrpl/rpc/v1/xrp_ledger.proto", :syntax => :proto3) do
  end
end

module Org
  module Xrpl
    module Rpc
      module V1
      end
    end
  end
end
