# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: org/xrpl/rpc/v1/xrp_ledger.proto for package 'org.xrpl.rpc.v1'

require 'grpc'
require 'org/xrpl/rpc/v1/xrp_ledger_pb'

module Org
  module Xrpl
    module Rpc
      module V1
        module XRPLedgerAPIService
          # RPCs available to interact with the XRP Ledger.
          # The gRPC API mimics the JSON API. Refer to xrpl.org for documentation
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'org.xrpl.rpc.v1.XRPLedgerAPIService'

            # Get account info for an account on the XRP Ledger.
            rpc :GetAccountInfo, GetAccountInfoRequest, GetAccountInfoResponse
            # Get the fee for a transaction on the XRP Ledger.
            rpc :GetFee, GetFeeRequest, GetFeeResponse
            # Submit a signed transaction to the XRP Ledger.
            rpc :SubmitTransaction, SubmitTransactionRequest, SubmitTransactionResponse
            # Get the status of a transaction
            rpc :GetTransaction, GetTransactionRequest, GetTransactionResponse
            # Get all validated transactions associated with a given account
            rpc :GetAccountTransactionHistory, GetAccountTransactionHistoryRequest, GetAccountTransactionHistoryResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
