# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/v1/tx.proto

require 'google/protobuf'

require 'rpc/v1/transaction_pb'
require 'rpc/v1/meta_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/v1/tx.proto", :syntax => :proto3) do
    add_message "rpc.v1.GetTxRequest" do
      optional :hash, :bytes, 1
      optional :binary, :bool, 2
    end
    add_message "rpc.v1.GetTxResponse" do
      optional :ledger_index, :uint32, 3
      optional :hash, :bytes, 4
      optional :validated, :bool, 5
      oneof :serialized_transaction do
        optional :transaction, :message, 1, "rpc.v1.Transaction"
        optional :transaction_binary, :bytes, 2
      end
      oneof :serialized_meta do
        optional :meta, :message, 6, "rpc.v1.Meta"
        optional :meta_binary, :bytes, 7
      end
    end
  end
end

module Rpc
  module V1
    GetTxRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.GetTxRequest").msgclass
    GetTxResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.v1.GetTxResponse").msgclass
  end
end
